### ISSUE TITLE
Stacks with varying image data storage configurations cannot be read

### ISSUE THREAD

**Issue by DylanMuir** [DylanMuir/TIFFStack#18]
`TIF` files may have arbitrary image sizes and storage configurations per frame. `TIFFStack` currently assumes that all images share a common size and storage configuration. This means stacks that do not adhere to this rule cannot be read properly, although a `TIFFStack` object can be successfully created.

Frames which have a differing storage configuration to the first frame, will raise an error when data from that frame is requested.

**Comment by DylanMuir** [comment]
I have created a branch [dev-different-image-config](https://github.com/DylanMuir/TIFFStack/tree/dev-different-image-config-in-stack) that hopefully fixes this bug. @ablot, please check if this works for you.

**Comment by DylanMuir** [comment]
@ablot Can I close this also?

**Comment by DylanMuir** [comment]
Now merged into `master` branch

**Comment by ablot** [comment]
I guess. There will still be an issue if something saves a stack with the information for row per strip only in the first frame and not after, but I have no tiff like that.

**Comment by DylanMuir** [comment]
Resolved by assuming that frames with no RPS information are stored by saving each entire frame in a contiguous chunk.
