### ISSUE TITLE
Resolved: Files with more than 2^16 images cannot be accessed correctly

### ISSUE THREAD

**Issue by ablot** [DylanMuir/TIFFStack#19]
I have a tiff created by scanimage 6 with 4 channels. It's big and in a single file:
```size(stack)

ans =

          40         256           1           4       24373
```

I can load the beginning with no problem
```
>> size(stack(:,:,1,1,16384))

ans =

    40   256
```

But after that, nothing can be read:
```
>> size(stack(:,:,1,1,16385))
Error using TIFFStack>TS_read_data_Tiff (line 1264)
*** TIFFStack: Could not read data from image file.

Error in TIFFStack/subsref (line 680)
                  tfData = TS_read_data_Tiff(oStack, S.subs, bLinearIndexing);

Caused by:
    Error using tifflib
    Input argument out of range.
```

Maybe not by chance, 16384*4 = 65536

I'm on branch master, commit b083ad97ca64b907cbcbff59babbbcb8ac01dc5d. I have the same problem with dev-different-image-config-in-stack.
Can it be a biggtif problem?

**Comment by ablot** [comment]
I just double checked. `ImageJ` can read the file properly and if I try to open without interleaving the channels:

```
>> size(stack_flat)

ans =

          40         256       97492
```

I have the save problem
```
>> size(stack_flat(:,:,65536))

ans =

    40   256

>> size(stack_flat(:,:,65537))
Error using TIFFStack>TS_read_data_Tiff (line 1264)
*** TIFFStack: Could not read data from image file.

Error in TIFFStack/subsref (line 680)
                  tfData = TS_read_data_Tiff(oStack, S.subs, bLinearIndexing);

Caused by:
    Error using tifflib
    Input argument out of range.
```

**Comment by DylanMuir** [comment]
As of `Matlab 2016a`, even `Matlab` can't access frame `65537`. `Tiff.setDirectory()` gives the same error.

**Comment by ablot** [comment]
great. Revert back to 2015 would be the simplest fix for now?

**Comment by DylanMuir** [comment]
Been a problem for a while...
[stackoverflow](http://stackoverflow.com/questions/23163315/matlab-cannot-read-multipage-tiff-beyond-216-frames)

**Comment by DylanMuir** [comment]
Sorry; `Matlab` *even up to* `2016a` can't do it.

**Comment by DylanMuir** [comment]
I'm not sure there is a fix possible...

**Comment by ablot** [comment]
no problem. I'll open with ImageJ and save multiple substacks with less than 2^16 frames each. I'll probably loose the scanimage header information but that's not critical for this example.

Thanks

**Comment by DylanMuir** [comment]
Hold up a moment. Let me see if using the slower access method works.

**Comment by DylanMuir** [comment]
There is a trial fix in the `dev-different-image-config-in-stack` branch. All frames can be accessed using the `tiffread` code.

**Comment by ablot** [comment]
Works like a charm :+1:

**Comment by DylanMuir** [comment]
Now merged into `master` branch.
