### ISSUE TITLE
.ImageDescription does not appear after getImageInfo()

### ISSUE THREAD

**Issue by machiroi** [DylanMuir/TIFFStack#20]
Hi,
I was using TIFFStack to load time-lapse tiff images saved by ImageJ (FIJI) on Mac with the following code.

```matlab
G = TIFFStack([Path FileName]);
Info = getImageInfo(G);
Head = strsplit(Info(1).ImageDescription,'\n');
TPF = cell2mat(Head(~cellfun(@isempty,strfind(Head,'finterval'))));
TPF = str2double(TPF((strfind(TPF,'=')+1):end));
```

To obtain the frame interval information I was using ImageDescription but the current version does not create that one. Is there another way to get such info? I can use a version released before December.

Makoto

**Comment by DylanMuir** [comment]
Hi Makoto,

You need to use the ‘getImageTags’ method, in the latest update. This is because for many large stacks, several of those text fields were using unreasonable amounts of Matlab’s memory.

I hope this helps, and I’m sorry for the change in usage.

Best regards,
Dylan.
