### ISSUE TITLE
Get offset position to find varying metadata

### ISSUE THREAD

**Issue by ablot** [DylanMuir/TIFFStack#23]
In scanimage files, every frame as a `Software` field. But all of them point to the same offset at the beginning of the file (32 for me). Is there a way to get the position of the field for a given frame so that I can know if my metadata are read from different places or not?
Basically I would like to access to `fpos` found in tiffread31_readtags.m L356 but I don't know how to do that from a stack.
I'm not sure if it would be a really useful feature outside of this only use case (in which case I could simply always load the first `Software` and ignore the rest)

**Comment by DylanMuir** [comment]
I'm not sure how to come up with a general solution for this, that doesn't add a 64-bit value to every tag for every image (when reading the tags). I'm also not sure if it's something that would be of general use. One could do it for particular tag types, but how to choose which ones?

If you strenuously disagree, reopen the issue and I'll reconsider :)
