### ISSUE TITLE
Slow loading from server compared with hard drive (much slower than ImageJ)

### ISSUE THREAD

**Issue by bpisaacoff** [DylanMuir/TIFFStack#25]
Hello, I'm seeing an issue where loading files from a server goes much slower than loading from the hard drive. I don't think it's a problem with the server, as ImageJ doesn't show such a drastic time difference. I've got the times below for the same 22 MB file. Any ideas what is going on or how to improve the load time? Using Windows 7, Matlab 2016b

Time to load in Matlab w/ TIFFStack
hard drive: 3.5s
server: 57s
`tic;tfstk=TIFFStack('filename');toc`

Time to load in ImageJ
hard drive: 1.8s
server: 2.85s

**Comment by DylanMuir** [comment]
Hi @bpisaacoff, when timing read operations you have to be very careful about caching, as you're probably aware. On my system (OS X 11.6, Matlab 2016a), starting always from a purged file cache, my timings for a 1GB file are:

TIFFStack:
`tic; ts=TIFFStack('HyperStack.tif');ts(:, :, :, :);toc`
   HDD: 15.9s
   Network: 44.8s (factor 2.87x)

Image J:
   HDD: 4.9s
   Network: 27.8s (factor 5.76x)

For a 22MB file:
TIFFStack:
   HDD: 1.0s
   Network: 1.2s

ImageJ
   HDD: 0.07s
   Network: 0.65s

So although `TIFFStack` is slower (which I'm a little unhappy with), `ImageJ` also sees a network slowdown. In fact, the network slowdown appears worse for `ImageJ` on my configuration. I am surprised that a 22MB file takes so long to load for you, though. Maybe you can try on a larger file, with purged caches, and see if there is still a drastic timing difference.

Best regards,
Dylan.

**Comment by bpisaacoff** [comment]
Hi Dylan, thanks so much for the quick and thorough feedback. Actually I'm not super clear about what you're referring to about clearing the cache. Could you clarify please? Thanks

**Comment by DylanMuir** [comment]
About file caching: https://msdn.microsoft.com/en-us/library/windows/desktop/aa364218(v=vs.85).aspx

Tool for clearing the cache: http://www.tmurgent.com/Tools/ATM/Default.aspx
