### ISSUE TITLE
ImageJ hyperstacks which mis-report the number of frames in the stack cause an error

### ISSUE THREAD

**Issue by xyza11808** [DylanMuir/TIFFStack#30]
hi, recently while using this code I have encountered with one issue:
the frame number read from tiff tag is larger than the real tiff frame number in my tif file, which was caused by the acquisition software automatically split the acquired frames into two tif files because of too many frames have been saved, and this error happens when reading the second tif file. it seems the code doesn't handle this condition.
so I was simply added following lines at line 1842:
if nAparrentSize < nNumFrames
    nAparrentSize = nNumFrames;
end
then is ok to read the file, I don't know if you have already provided a solution to solve this problem?

**Comment by DylanMuir** [comment]
Hi, thanks for your message.

I don't completely understand the problem. Could you please let me know exactly what error message is being reported by matlab? You could copy and paste the error messages from the command window.

How are you reading the frame number from the TIFF tags? Is the TIFF file an ImageJ file? Could you please send me an example TIFF file that raises an error, or make it available to download?

**Comment by xyza11808** [comment]
hi, such a quick reply!!
I will give a thorough description about the tif files:
during my acquisition, because too much frames need to be saved, the software automatically save all frames into two tif files, but somehow the software  set the numberFrame value of all tif files as the sum of all frames. for example,if the first tif file have 10000 frames, and second file have 3000 frames, then the software set all numberFrame values of two tif files as 13000. and the value of 'nNumFrames' is also 13000 for both files using your code.
![default](https://user-images.githubusercontent.com/10867075/33825826-d93b8d52-de9d-11e7-9a25-d8e98c8d44cb.JPG)
attached is the error info, which happens when loading the second tif file.

**Comment by DylanMuir** [comment]
Thanks. What software are you using to save / split the TIFF files? Could you please send me an example TIFF file that raises an error, or make it available to download?

**Comment by xyza11808** [comment]
using the image J plug-in software: micro-manager 2.0 
https://drive.google.com/file/d/1_meoCFco278MGmZVpJYJBJ_2HjPoQRD7/view?usp=sharing
don't know whether you can open this share?

**Comment by DylanMuir** [comment]
Thanks, I am downloading the file.

**Comment by DylanMuir** [comment]
Ok, I am testing a change which tries to recover gracefully from this mis-formed TIFF file, but I would appreciate it if you send a bug report to mico-manager. This is an error on their end.

**Comment by xyza11808** [comment]
yes, I will try with that, and thanks for your excellent work!

**Comment by DylanMuir** [comment]
`TIFFStack` now reports these mis-formed stacks with a warning and attempts to continue. Fixed in commit [6492032](https://github.com/DylanMuir/TIFFStack/commit/6492032e4e2c0e0cda7a1ba8484cee76c0a02672).
