### ISSUE TITLE
tiffstack not opening the file

### ISSUE THREAD

**Issue by alecrimi** [DylanMuir/TIFFStack#31]
Hi,
I am using Matlab 2018R with installed Tensormap and TiffStack.
I am trying to load one of those terrible multislice TIFF saved from Imagej which save the info only of the first. Imread is only able to read the first. 
When I simply do

`tsStack = TIFFStack('left_c.tif');`
I get this error

`--- MappedTensor: Compiling MEX functions.
Warning: --- MappedTensor: Could not compile MEX functions.  Using slow matlab versions. 
> In MappedTensor>GetMexFunctionHandles (line 2173)
  In MappedTensor (line 204)
  In TIFFStack>OpenImageJBigStack (line 1885)
  In TIFFStack (line 247) 
Warning: --- MappedTensor/delete: Could not delete temporary file.
       Error: Invalid file identifier. Use fopen to generate a valid file identifier. 
> In MappedTensor/delete (line 408)
  In MappedTensor (line 200)
  In TIFFStack>OpenImageJBigStack (line 1885)
  In TIFFStack (line 247) 
Error using TIFFStack (line 484)
*** TIFFStack: Could not open file [C:\Users\Administrator\Documents\ruiqin\left_c.tif].

Caused by:
    Error using fopen
    First input must be a file name or a file identifier.`

any idea?

**Comment by DylanMuir** [comment]
Hi Alessandro

That seems strange. There’s a few problems here: the first is that `mex` may not be correctly configured, so you get the error about compilation failing. You could try to make sure that `mex` works, and then this may fix your problems.

But `TIFFStack` should work even without `mex`, so this is weird. Could you try turning debugging on with the `debug if error` command, and see what’s happening when the error occurs?

**Comment by XhXue** [comment]
Hi,
I'm using this code with matlab2018b to load my big tiff files converted by ImageJ (primary files are .fli).
This might be silly since I'm quite new to matlab. I'm running it using X2toGo on the server and tried:
tsStack = TIFFStack ('/xx/xx/Rec3.tif'); %%the full file path

And it showed me this:
Error using TIFFStack
Error: File: TIFFStack.m Line: 180 Column: 46
Invalid use of operator

Do I have to put my tif files on the same path with the code? Or any idea about this error?

Thank you in advance!

**Comment by DylanMuir** [comment]
Hi XhXue,
The TIFFStack unit tests pass on 2018b (at least on OS X), so I’m not sure what your problem could be. How big is your file? Can you reproduce this on a file that is small enough to send to me?

**Comment by DylanMuir** [comment]
You don't need to have the file on the same path as the code, by the way.

**Comment by XhXue** [comment]
> Hi XhXue, The TIFFStack unit tests pass on 2018b (at least on OS X), so I’m not sure what your problem could be. How big is your file? Can you reproduce this on a file that is small enough to send to me?

Hi Dylan,

Thank you very much for the reply! 
My matlab version is 2018a, before I tried your code with big tiff files that are larger than 4GB, and then I split them into small substacks (around 2.5GB), it shows the same error. Do you think it could be the old version issue?
Thank you!
