### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by scottclowe** [DylanMuir/TIFFStack#4]
Hi @DylanMuir,
We would like to use your code as a dependency in a toolbox we (myself + @swkeemink) are developing.
However, there is no LICENSE or COPYING file in the repository, and no license details are mentioned in the README, so it is not clear what license the code is distributed under and we cannot use your package unless it is explicitly distributed under an open source license.

Could you add a LICENSE file to clear this up?

If you've not licensed code before, [here is a handy site](http://choosealicense.com/) for helping to pick an open source license.

**Comment by DylanMuir** [comment]
I added licensing information to `README.md` and `LICENSE.md`.

**Comment by scottclowe** [comment]
Great, thanks!
